// Package firewall builds the host firewall allow and ban lists from the
// database (D-69). sbc-api writes them as JSON to a shared directory on
// every change; sbc-fwsync (a small program on the host, the only place
// with CAP_NET_ADMIN) turns them into nftables set contents atomically.
package firewall

import (
	"encoding/json"
	"fmt"
	"net"
	"sort"
	"strings"
	"time"

	"github.com/imfanee/supersbc/internal/model"
)

// Banned is one banned address with the seconds left (0 = permanent).
type Banned struct {
	IP      string `json:"ip"`
	Seconds int    `json:"seconds"`
}

// Export is what sbc-api writes and sbc-fwsync reads.
type Export struct {
	GeneratedAt time.Time `json:"generated_at"`
	// Customers are the authorised customer addresses (IPs or CIDR blocks).
	Customers []string `json:"customers"`
	// Carriers are carrier gateway hosts (IP or hostname) and their extra
	// signalling sources (IPs or CIDR blocks); hostnames are resolved by sbc-fwsync.
	Carriers []string `json:"carriers"`
	Banned   []Banned `json:"banned"`
}

// Build assembles the export from the database rows.
func Build(ips []model.CustomerIP, carriers []model.Carrier, banned []model.BannedIP, now time.Time) Export {
	ex := Export{GeneratedAt: now.UTC(), Customers: []string{}, Carriers: []string{}, Banned: []Banned{}}
	seen := map[string]bool{}
	for _, ip := range ips {
		if c := strings.TrimSpace(ip.IPCIDR); c != "" && !seen[c] {
			seen[c] = true
			ex.Customers = append(ex.Customers, c)
		}
	}
	seen = map[string]bool{}
	for _, c := range carriers {
		if c.Status != "active" {
			continue
		}
		for _, src := range append([]string{c.GatewayHost}, c.SignallingSources...) {
			if src = strings.TrimSpace(src); src != "" && !seen[src] {
				seen[src] = true
				ex.Carriers = append(ex.Carriers, src)
			}
		}
	}
	for _, b := range banned {
		secs := 0
		if b.ExpiresAt != nil {
			left := b.ExpiresAt.Sub(now)
			if left <= 0 {
				continue
			}
			secs = int(left.Seconds()) + 1
		}
		ex.Banned = append(ex.Banned, Banned{IP: b.IP, Seconds: secs})
	}
	sort.Strings(ex.Customers)
	sort.Strings(ex.Carriers)
	return ex
}

// JSON encodes the export.
func (ex Export) JSON() []byte {
	b, _ := json.MarshalIndent(ex, "", "  ")
	return append(b, '\n')
}

// Parse decodes an export file.
func Parse(b []byte) (Export, error) {
	var ex Export
	err := json.Unmarshal(b, &ex)
	return ex, err
}

// Resolver turns a hostname into addresses; net.LookupHost in production.
type Resolver func(host string) ([]string, error)

// Script renders the nftables commands that make the three sets of the
// table equal to the export, as one transaction (nft -f applies it
// atomically). IPv4 only: the sets are ipv4_addr. Hostnames that do not
// resolve are skipped and reported.
func Script(ex Export, table string, resolve Resolver) (script string, problems []string) {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by sbc-fwsync from an export of %s\n", ex.GeneratedAt.Format(time.RFC3339))
	set := func(name string, elems []string) {
		fmt.Fprintf(&b, "flush set %s %s\n", table, name)
		if len(elems) > 0 {
			fmt.Fprintf(&b, "add element %s %s { %s }\n", table, name, strings.Join(elems, ", "))
		}
	}
	set("customers", ipv4Only(ex.Customers, &problems))
	var carriers []string
	for _, c := range ex.Carriers {
		if _, _, err := net.ParseCIDR(c); err == nil || net.ParseIP(c) != nil {
			carriers = append(carriers, c)
			continue
		}
		addrs, err := resolve(c)
		if err != nil || len(addrs) == 0 {
			problems = append(problems, fmt.Sprintf("carrier host %q does not resolve", c))
			continue
		}
		carriers = append(carriers, addrs...)
	}
	set("carriers", ipv4Only(carriers, &problems))
	var banned []string
	for _, bn := range ex.Banned {
		ip := net.ParseIP(bn.IP)
		if ip == nil || ip.To4() == nil {
			continue
		}
		if bn.Seconds > 0 {
			banned = append(banned, fmt.Sprintf("%s timeout %ds", bn.IP, bn.Seconds))
		} else {
			banned = append(banned, bn.IP)
		}
	}
	set("banned", banned)
	return b.String(), problems
}

// ipv4Only keeps IPv4 addresses and CIDR blocks, deduplicated and sorted.
func ipv4Only(in []string, problems *[]string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		var ok bool
		if ip, ipnet, err := net.ParseCIDR(s); err == nil {
			ok = ip.To4() != nil
			s = ipnet.String()
		} else if ip := net.ParseIP(s); ip != nil {
			ok = ip.To4() != nil
			s = ip.String()
		} else {
			*problems = append(*problems, fmt.Sprintf("not an address: %q", s))
			continue
		}
		if ok && !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
