package admin

import _ "embed"

// openapiEmbedded is the OpenAPI 3.1 document generated by "make openapi"
// (swag v2). It is embedded so the binary serves /api/docs without files.
//
//go:embed openapi/swagger.json
var openapiEmbedded []byte
