package invoice

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/shopspring/decimal"
)

// PDF renders the invoice. Amounts are printed at two decimals for the
// totals and six for the per-destination lines, straight from the stored
// decimals (never float).
func (s *Service) PDF(inv *Invoice, payments []Allocation) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(inv.Number, true)
	pdf.SetAuthor(s.Op.Name, true)
	pdf.SetMargins(18, 18, 18)
	pdf.SetAutoPageBreak(true, 20)
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(120, 120, 120)
		foot := s.Op.Footer
		if foot == "" {
			foot = "Prepaid usage invoice generated by SuperSBC. Amounts are in " + inv.Currency + "."
		}
		pdf.CellFormat(0, 5, foot, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "R", false, 0, "")
	})
	pdf.AddPage()

	// Header: issuer left, invoice identity right.
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(20, 20, 20)
	name := s.Op.Name
	if name == "" {
		name = "SuperSBC"
	}
	pdf.CellFormat(100, 8, name, "", 0, "L", false, 0, "")
	pdf.CellFormat(0, 8, "INVOICE", "", 1, "R", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(80, 80, 80)
	addr := strings.Split(strings.ReplaceAll(s.Op.Address, "|", "\n"), "\n")
	right := []string{
		"Number: " + inv.Number,
		"Period: " + inv.PeriodStart.Format("2 Jan 2006") + " to " + inv.PeriodEnd.Add(-time.Second).Format("2 Jan 2006") + periodKind(inv.Kind),
		"Issued: " + inv.CreatedAt.UTC().Format("2 Jan 2006"),
		"Currency: " + inv.Currency,
	}
	for i := 0; i < len(addr) || i < len(right); i++ {
		l, r := "", ""
		if i < len(addr) {
			l = strings.TrimSpace(addr[i])
		}
		if i < len(right) {
			r = right[i]
		}
		pdf.CellFormat(100, 5, l, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5, r, "", 1, "R", false, 0, "")
	}
	pdf.Ln(4)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(20, 20, 20)
	kind := "Customer"
	if inv.OwnerType == "carrier" {
		kind = "Carrier"
	}
	pdf.CellFormat(0, 6, kind+": "+inv.OwnerName, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(0, 5, "Account "+inv.AccountID.String(), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// Balance summary.
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(0, 6, "Account summary", "B", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	row := func(label, amount string, bold bool) {
		if bold {
			pdf.SetFont("Helvetica", "B", 9)
		}
		pdf.CellFormat(120, 6, label, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 6, money(amount, 2), "", 1, "R", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
	}
	row("Opening balance", inv.Opening, false)
	row("Top-ups", inv.Topups, false)
	if inv.OwnerType == "customer" {
		row("Call charges", inv.Charges, false)
	} else {
		row("Call costs", inv.Costs, false)
	}
	row("Adjustments", inv.Adjustments, false)
	row("Refunds", inv.Refunds, false)
	row("Closing balance", inv.Closing, true)
	pdf.Ln(3)
	usage := inv.Charges
	if inv.OwnerType == "carrier" {
		usage = inv.Costs
	}
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(120, 7, "Total usage for the period", "T", 0, "L", false, 0, "")
	pdf.CellFormat(0, 7, money(negate(usage), 2), "T", 1, "R", false, 0, "")
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(0, 5, fmt.Sprintf("%d answered calls, %s billed", inv.Calls, hms(inv.BilledSeconds)), "", 1, "L", false, 0, "")
	pdf.SetTextColor(20, 20, 20)
	pdf.Ln(2)
	// Payments applied to this invoice and what remains.
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(0, 6, "Payments applied to this invoice", "B", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	paid := decimal.Zero
	for _, p := range payments {
		amt, _ := decimal.NewFromString(p.Amount)
		paid = paid.Add(amt)
		label := p.ReceivedAt.Format("2 Jan 2006")
		if p.Reference != "" {
			label += ", ref " + p.Reference
		}
		pdf.CellFormat(120, 6, label, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 6, money(p.Amount, 2), "", 1, "R", false, 0, "")
	}
	if len(payments) == 0 {
		pdf.CellFormat(0, 6, "No payments recorded against this invoice.", "", 1, "L", false, 0, "")
	}
	amount, _ := decimal.NewFromString(inv.Amount)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(120, 7, "Balance due on this invoice", "T", 0, "L", false, 0, "")
	pdf.CellFormat(0, 7, amount.Sub(paid).StringFixed(2), "T", 1, "R", false, 0, "")
	pdf.Ln(4)

	// Usage per destination.
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(0, 6, "Usage by destination", "B", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(240, 240, 240)
	pdf.CellFormat(90, 6, "Destination", "", 0, "L", true, 0, "")
	pdf.CellFormat(25, 6, "Calls", "", 0, "R", true, 0, "")
	pdf.CellFormat(30, 6, "Billed", "", 0, "R", true, 0, "")
	pdf.CellFormat(0, 6, "Amount", "", 1, "R", true, 0, "")
	pdf.SetFont("Helvetica", "", 8)
	for _, l := range inv.Lines {
		dest := l.Destination
		if dest == "" {
			dest = "(unknown)"
		}
		pdf.CellFormat(90, 5, dest, "", 0, "L", false, 0, "")
		pdf.CellFormat(25, 5, fmt.Sprint(l.Calls), "", 0, "R", false, 0, "")
		pdf.CellFormat(30, 5, hms(l.BilledSeconds), "", 0, "R", false, 0, "")
		pdf.CellFormat(0, 5, money(l.Amount, 6), "", 1, "R", false, 0, "")
	}
	if len(inv.Lines) == 0 {
		pdf.CellFormat(0, 5, "No answered calls in the period.", "", 1, "L", false, 0, "")
	}
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func money(s string, places int32) string {
	d, err := decimal.NewFromString(s)
	if err != nil {
		return s
	}
	return d.StringFixed(places)
}

func negate(s string) string {
	d, err := decimal.NewFromString(s)
	if err != nil {
		return s
	}
	return d.Neg().String()
}

func hms(sec int64) string {
	return fmt.Sprintf("%02d:%02d:%02d", sec/3600, sec%3600/60, sec%60)
}

func periodKind(kind string) string {
	if kind == "custom" {
		return " (custom period)"
	}
	return ""
}
